spring.jpa.open-in-view: false

spring:
  flyway:
    enabled: false

certificate:
  domain:
    datasource:
      poolName: search-domain-cp
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: org.mariadb.jdbc.Driver
      jdbcUrl: "jdbc:mysql://localhost:3306/searchmanager"
      username: root
      password: root
      auto-commit: false
      sqlScriptEncoding: UTF-8
      connectionTimeout: 3000
      idleTimeout: 0
      maxLifetime: 60000
      maximumPoolSize: 5
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL57Dialect
          format_sql: true
          show-sql: true
          order_inserts: true
          order_updates: true
          jdbc:
            batch_size: 500
            fetch_size: 500
            batch_versioned_data: true

dynacode:
  scheduled:
    delay: 10000