version: '3'

services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: search-manager
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASES=searchmanager
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./docker/mysql/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
